codecov:
  token: # GitHub Actionsで自動設定
  bot: false
  ci:
    - github-actions
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches:
          - main
      backend:
        target: 80%
        threshold: 1%
        flags:
          - backend
      frontend:
        target: 80%
        threshold: 1%
        flags:
          - frontend
      ml:
        target: 70%
        threshold: 1%
        flags:
          - ml
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

flags:
  backend:
    paths:
      - backend/app
  frontend:
    paths:
      - frontend/src
  ml:
    paths:
      - ml

